version: '3'

services:
  app:
    image: adxl/bng-app:latest
    environment:
      VITE_API_URL: '@VITE_API_URL@'
    ports:
      - 3000:3000
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
